title: 'Gaurush Hiranandani'
description: 'Applied Scientist (II) at Amazon (Search Science and AI). <br /> Email: firstname [dot] lastname [at] gmail [dot] com'
logo: /assets/img/logo_latest.jpg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
# remote_theme: mmistakes/hpstr-jekyll-theme
