title: 'Gaurush Hiranandani'
description: 'Staff Applied Scientist at Typeface AI'
logo: /assets/img/logo_latest.jpg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
is_user_page: false
# remote_theme: mmistakes/hpstr-jekyll-theme
