title: 'Gaurush Hiranandani'
description: 'Ph.D. Candidate, Department of Computer Science, University of Illinois at Urbana-Champaign (UIUC). <br /> Email: gaurush2 [at] illinois.edu'
logo: /assets/img/logo_latest.jpg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
# remote_theme: mmistakes/hpstr-jekyll-theme
