title: 'Gaurush Hiranandani'
description: 'Ph.D. Student, Department of Computer Science, University of Illinois Urbana-Champaign (UIUC). <br /> Email: gaurush2 [at] illinois.edu'
logo: /assets/img/logo.JPG
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
# remote_theme: mmistakes/hpstr-jekyll-theme
